#!/usr/bin/env python3

import argparse
import sys
import os

def clean_text(text):
    # Keeps printable ASCII characters and common whitespace: tab, newline, carriage return
    return ''.join(c for c in text if 32 <= ord(c) <= 126 or c in '\n\r\t')

def main():
    parser = argparse.ArgumentParser(description="Remove special characters generated by ChatGPT from a plain text file.")
    parser.add_argument("input", help="Input text file path")
    parser.add_argument("output", nargs="?", help="(Optional) Output file path. If not provided, prints to stdout.")

    args = parser.parse_args()

    # Validate input file
    if not os.path.isfile(args.input):
        print(f"Error: File not found - {args.input}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(args.input, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"Failed to read input file: {e}", file=sys.stderr)
        sys.exit(1)

    cleaned = clean_text(content)

    if args.output:
        try:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(cleaned)
            print(f"Cleaned text written to {args.output}")
        except Exception as e:
            print(f"Failed to write output file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(cleaned)

if __name__ == "__main__":
    main()
